# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RendezVous' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RendezVous
  pod 'lottie-ios', :path => '../node_modules/lottie-ios'
  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


  pod 'RNI18n', :path => '../node_modules/react-native-i18n'

  target 'RendezVousTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
